#!/usr/bin/env bash
# Netra — P1–P5 observability surface unit gate (no root)
#
# Focused suite for the packages and API routes added with the P1–P5
# metadata surfaces (TLS/DoH, fleet, shadow SaaS, microseg, prevention,
# exfil/lateral/ECH boards, etc.). Kept as an explicit script so CI and
# local agents run the same command, not a one-off `go test` line.
#
# Usage:
#   ./scripts/ci-p1-p5-unit.sh
#   RACE=0 ./scripts/ci-p1-p5-unit.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RACE="${RACE:-1}"
COUNT="${COUNT:-1}"

PKGS=(
  ./internal/tlsfp/...
  ./internal/encdns/...
  ./internal/ainet/...
  ./internal/appcat/...
  ./internal/automitigate/...
  ./internal/catdeny/...
  ./internal/compliance/...
  ./internal/destrisk/...
  ./internal/dnsintel/...
  ./internal/echblind/...
  ./internal/exfil/...
  ./internal/experience/...
  ./internal/identitydraft/...
  ./internal/lateral/...
  ./internal/microseg/...
  ./internal/policypack/...
  ./internal/prevention/...
  ./internal/shadowsaas/...
  ./internal/fleet/...
  ./internal/intel/...
)

echo "==> P1–P5 package unit tests (count=${COUNT})"
go test "${PKGS[@]}" -count="$COUNT"

echo "==> API registration + surface handlers (routes / TLS / intel live)"
go test ./internal/api/ -run 'RegisteredAPIRoutes|TLSFingerprint|IntelFeed|AIDestinations' -count="$COUNT"

if [[ "$RACE" == "1" ]]; then
  echo "==> P1–P5 race detector"
  go test "${PKGS[@]}" -race -count=1
fi

echo "==> PASS ci-p1-p5-unit"
