import { useEffect,useMemo,useState } from 'react';
import { api } from '../api';
import LiveFlowTerminal from '../components/LiveFlowTerminal';
type Kind='pod'|'vm';
type Detail={kind:Kind;name:string;namespace:string;phase?:string;node?:string;podIP?:string;podName?:string;running?:boolean;labels?:Record<string,string>;recommendedSelector:Record<string,string>;lockdownPolicy:string;lockedDown:boolean;policies:{name:string;namespace:string;lockdown:boolean}[]};
export default function Workloads({kind}:{kind:Kind}){const [ns,setNs]=useState(''),[q,setQ]=useState(''),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[detail,setDetail]=useState<Detail|null>(null),[msg,setMsg]=useState(''),[candidate,setCandidate]=useState(''),[receipt,setReceipt]=useState<any>(null);const title=kind==='pod'?'Pods':'VMs';
 async function refresh(){try{const path=kind==='pod'?`/api/v1/pods${ns?`?namespace=${encodeURIComponent(ns)}`:''}`:`/api/v1/vms${ns?`?namespace=${encodeURIComponent(ns)}`:''}`;const x=await api<any>(path);setItems(x.items||[])}catch(e){setMsg(String(e))}}
 useEffect(()=>{void refresh()},[ns,kind]); async function open(x:any){setSelected(x);try{setDetail(await api<Detail>(`/api/v1/workloads/${kind}/${encodeURIComponent(x.namespace)}/${encodeURIComponent(x.name)}`))}catch(e){setMsg(String(e))}}
 const filtered=useMemo(()=>items.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[items,q]);
 async function lockdown(){if(!detail)return;const x=await api<any>('/api/v1/policies/lockdown',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({namespace:detail.namespace,name:detail.name,kind,selector:detail.recommendedSelector})});setCandidate(JSON.stringify(x));setReceipt(null);setMsg('Lockdown policy generated. Preflight before apply.')}
 async function preflight(){if(!candidate)return;const x=await api<any>('/api/v1/policies/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:candidate});setReceipt(x);setMsg(x.dryRun?.passed?'Preflight passed.':'Preflight failed.')}
 async function apply(){if(!candidate||!receipt?.receipt?.token)return;const risk=(receipt.plan?.risk||'low').toLowerCase();if(['high','critical'].includes(risk)&&!confirm(`Risk ${risk}. Apply?`))return;const headers:any={'Content-Type':'application/json','X-Netra-Plan-Token':receipt.receipt.token};if(['high','critical'].includes(risk))headers['X-Netra-Confirm-Risk']=risk;await api('/api/v1/policies/apply?dryRun=false',{method:'POST',headers,body:candidate});setMsg('Applied.');if(selected)await open(selected);await refresh()}
 async function unlock(){if(!detail||!confirm(`Unlock ${detail.namespace}/${detail.name}?`))return;await api(`/api/v1/policies/lockdown/${encodeURIComponent(detail.namespace)}/${encodeURIComponent(detail.name)}`,{method:'DELETE'});setMsg('Unlocked.');if(selected)await open(selected);await refresh()}
 return <div className="grid"><section className="card span3"><p className="eyebrow">{kind==='pod'?'WORKLOADS':'KUBEVIRT'}</p><h2>{title}</h2><div className="toolbar"><input value={ns} placeholder="namespace (all)" onChange={e=>setNs(e.target.value)}/><input value={q} placeholder="search" onChange={e=>setQ(e.target.value)}/><button onClick={refresh}>Refresh</button></div>{msg&&<p>{msg}</p>}</section><section className="card span2"><h3>{title} inventory</h3><div className="list">{filtered.map(x=><button key={`${x.namespace}/${x.name}`} onClick={()=>open(x)}><span><b>{x.name}</b><small style={{display:'block'}}>{x.namespace}{x.node?` · ${x.node}`:''}{x.podIP?` · ${x.podIP}`:''}</small></span><span>{x.lockedDown?'LOCKED':x.phase||(x.running?'Running':'—')}</span></button>)}</div></section><section className="card"><h3>Entity</h3>{detail?<><p><b>{detail.namespace}/{detail.name}</b></p><p>{detail.node}{detail.podIP?` · ${detail.podIP}`:''}</p><div className="toolbar"><button className="danger" onClick={lockdown} disabled={detail.lockedDown}>Lock down</button><button onClick={unlock} disabled={!detail.lockedDown}>Unlock</button><button onClick={preflight} disabled={!candidate}>Preflight</button><button className="primary" onClick={apply} disabled={!receipt?.receipt?.token}>Apply</button></div></>:<p>Select a {kind}.</p>}</section>{detail&&<section className="card span3"><h3>Live flows for {detail.namespace}/{detail.name}</h3><LiveFlowTerminal initial={{namespace:detail.namespace,pod:detail.podName||detail.name,direction:'EGRESS'}} lockedScope showFilters/></section>}</div>}
