{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: netra
automountServiceAccountToken: true
{{- end }}
---
{{- if and .Values.agent.enabled .Values.agentServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agentServiceAccount.name }}
  labels:
    app.kubernetes.io/name: netra-agent
automountServiceAccountToken: false
{{- end }}
