apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netra.name" . }}
  labels: {{- include "netra.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netra.name" . }}-agent
automountServiceAccountToken: false
