import { useEffect, useRef, useState } from 'react';
import { api, authHeaders } from '../api';
import TerminalFrame from './TerminalFrame';
import { endpointName, tuple, verdictClass } from '../lib/flow';

export type FlowFilter={direction:string;verdict:string;protocol:string;namespace:string;pod:string;destination:string};
export default function LiveFlowTerminal({title='observer.GetFlows / filtered',initial,lockedScope=false,showFilters=true}:{title?:string;initial?:Partial<FlowFilter>;lockedScope?:boolean;showFilters?:boolean}){
 const [flows,setFlows]=useState<any[]>([]),[drops,setDrops]=useState<any[]>([]); const [filter,setFilter]=useState<FlowFilter>({direction:'EGRESS',verdict:'',protocol:'',namespace:'',pod:'',destination:'',...initial}); const [run,setRun]=useState(0); const ctrl=useRef<AbortController|undefined>(undefined);
 useEffect(()=>{setFilter(f=>({...f,...initial}));setFlows([]);setRun(x=>x+1)},[initial?.namespace,initial?.pod]);
 useEffect(()=>{ctrl.current?.abort();const c=new AbortController();ctrl.current=c;const q=new URLSearchParams({number:'100',...Object.fromEntries(Object.entries(filter).filter(([,v])=>v))});(async()=>{try{const r=await fetch('/api/v1/flows/stream?'+q,{headers:authHeaders(),signal:c.signal});if(!r.ok)throw new Error(await r.text());if(!r.body)return;const rd=r.body.getReader(),dec=new TextDecoder();let buf='';for(;;){const res=await rd.read();if(res.done)break;buf+=dec.decode(res.value,{stream:true});let i;while((i=buf.indexOf('\n\n'))>=0){const part=buf.slice(0,i);buf=buf.slice(i+2);const line=part.split('\n').find(v=>v.startsWith('data: '));if(line&&part.includes('event: flow')){const f=JSON.parse(line.slice(6));setFlows(old=>[f,...old].slice(0,250))}}}}catch(e:any){if(e.name!=='AbortError')console.error(e)}})();return()=>c.abort()},[run]);
 async function explain(){try{const q=new URLSearchParams({limit:'20'});if(filter.namespace)q.set('namespace',filter.namespace);if(filter.pod)q.set('pod',filter.pod);const x=await api<any>('/api/v1/drops/explain?'+q);setDrops(x.findings||[])}catch(e){console.error(e)}}
 return <div className="grid" style={{margin:0}}>{showFilters&&<section className="card span3"><div className="filters">{Object.entries(filter).map(([k,v])=><label key={k}>{k}<input value={v} disabled={lockedScope&&(k==='namespace'||k==='pod')} onChange={e=>setFilter({...filter,[k]:e.target.value})}/></label>)}<button className="btn-refresh" onClick={()=>{setFlows([]);setRun(x=>x+1)}}>Reconnect</button><button className="btn-diag" onClick={explain}>Explain drops</button></div></section>}<div className="span3"><TerminalFrame title={title}><div className="flowhead"><span>VERDICT</span><span>DIR</span><span>SOURCE → DESTINATION</span><span>NETWORK</span></div>{flows.map((f,i)=><div className="flowrow" key={i}><span className={verdictClass(f.verdict)}>{f.verdict}</span><span className={f.trafficDirection==='INGRESS'?'dir-ingress':'dir-egress'}>{f.trafficDirection}</span><span>{endpointName(f.source)} → {endpointName(f.destination)}</span><span>{tuple(f)}</span></div>)}</TerminalFrame></div>{drops.length>0&&<section className="card span3"><h3>Recent drop findings</h3>{drops.map((d,i)=><div className="dropcard" key={i}><b>{d.explanation||'Dropped flow'}</b><span>{d.source} · {d.code||d.reason||'unknown'}</span></div>)}</section>}</div>
}
